
import NavBar from '@/components/shared/NavBar';
import Footer from '@/components/shared/Footer';
import CTASection from '@/components/shared/CTASection';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html
      lang="en" 
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

   
        <NavBar />
        <main className="mt-16 md:mt-20">{children}</main>

        <CTASection />
        <Footer/>
        
      </body>
    </html>
  );
}
