import { Hind_Siliguri, Noto_Serif_Bengali, Inter } from 'next/font/google';
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const hindSiliguri = Hind_Siliguri({
  subsets: ['bengali', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-hind',
  display: 'swap',
});

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ['bengali', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto-serif',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" 
      className={`${hindSiliguri.variable} ${notoSerifBengali.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Toaster/>
        
        <main className="">{children}</main>

        
        
      </body>
    </html>
  );
}
